/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosInvoiceRouteImport } from './routes/pos-invoice'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KitchenDashboardRouteImport } from './routes/kitchen-dashboard'
import { Route as CounterDashboardRouteImport } from './routes/counter-dashboard'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignupVerifyRouteImport } from './routes/(auth)/signup-verify'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardRestaurantManagementRouteRouteImport } from './routes/dashboard/restaurant-management/route'
import { Route as DashboardReservationsRouteRouteImport } from './routes/dashboard/reservations/route'
import { Route as DashboardPurchaseManageRouteRouteImport } from './routes/dashboard/purchase-manage/route'
import { Route as DashboardProductionRouteRouteImport } from './routes/dashboard/production/route'
import { Route as DashboardOrdersRouteRouteImport } from './routes/dashboard/orders/route'
import { Route as DashboardFoodManagementRouteRouteImport } from './routes/dashboard/food-management/route'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardRestaurantManagementIndexRouteImport } from './routes/dashboard/restaurant-management/index'
import { Route as DashboardReservationsIndexRouteImport } from './routes/dashboard/reservations/index'
import { Route as DashboardPurchaseManageIndexRouteImport } from './routes/dashboard/purchase-manage/index'
import { Route as DashboardProductionIndexRouteImport } from './routes/dashboard/production/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardFoodManagementIndexRouteImport } from './routes/dashboard/food-management/index'
import { Route as DashboardChatsIndexRouteImport } from './routes/dashboard/chats/index'
import { Route as DashboardAppsIndexRouteImport } from './routes/dashboard/apps/index'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsDisplayRouteImport } from './routes/dashboard/settings/display'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings/appearance'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard/settings/account'
import { Route as DashboardRestaurantManagementManageTablesIndexRouteImport } from './routes/dashboard/restaurant-management/manage-tables/index'
import { Route as DashboardRestaurantManagementManageKitchensIndexRouteImport } from './routes/dashboard/restaurant-management/manage-kitchens/index'
import { Route as DashboardReservationsUnavailableDayIndexRouteImport } from './routes/dashboard/reservations/unavailable-day/index'
import { Route as DashboardReservationsSettingsIndexRouteImport } from './routes/dashboard/reservations/settings/index'
import { Route as DashboardPurchaseManageSupplierManageIndexRouteImport } from './routes/dashboard/purchase-manage/supplier-manage/index'
import { Route as DashboardPurchaseManageSupplierLedgerIndexRouteImport } from './routes/dashboard/purchase-manage/supplier-ledger/index'
import { Route as DashboardPurchaseManageStockOutIngredientsIndexRouteImport } from './routes/dashboard/purchase-manage/stock-out-ingredients/index'
import { Route as DashboardPurchaseManageReturnInvoiceIndexRouteImport } from './routes/dashboard/purchase-manage/return-invoice/index'
import { Route as DashboardPurchaseManagePurchaseReturnIndexRouteImport } from './routes/dashboard/purchase-manage/purchase-return/index'
import { Route as DashboardPurchaseManagePurchaseItemIndexRouteImport } from './routes/dashboard/purchase-manage/purchase-item/index'
import { Route as DashboardPurchaseManageAddPurchaseIndexRouteImport } from './routes/dashboard/purchase-manage/add-purchase/index'
import { Route as DashboardProductionSetProductionUnitIndexRouteImport } from './routes/dashboard/production/set-production-unit/index'
import { Route as DashboardProductionProductionSettingIndexRouteImport } from './routes/dashboard/production/production-setting/index'
import { Route as DashboardProductionProductionSetListIndexRouteImport } from './routes/dashboard/production/production-set-list/index'
import { Route as DashboardProductionAddProductionIndexRouteImport } from './routes/dashboard/production/add-production/index'
import { Route as DashboardFoodManagementManageFoodIndexRouteImport } from './routes/dashboard/food-management/manage-food/index'
import { Route as DashboardFoodManagementManageCategoryIndexRouteImport } from './routes/dashboard/food-management/manage-category/index'
import { Route as DashboardFoodManagementManageAddonsIndexRouteImport } from './routes/dashboard/food-management/manage-addons/index'

const PosInvoiceRoute = PosInvoiceRouteImport.update({
  id: '/pos-invoice',
  path: '/pos-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenDashboardRoute = KitchenDashboardRouteImport.update({
  id: '/kitchen-dashboard',
  path: '/kitchen-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterDashboardRoute = CounterDashboardRouteImport.update({
  id: '/counter-dashboard',
  path: '/counter-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupVerifyRoute = authSignupVerifyRouteImport.update({
  id: '/signup-verify',
  path: '/signup-verify',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRestaurantManagementRouteRoute =
  DashboardRestaurantManagementRouteRouteImport.update({
    id: '/restaurant-management',
    path: '/restaurant-management',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReservationsRouteRoute =
  DashboardReservationsRouteRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPurchaseManageRouteRoute =
  DashboardPurchaseManageRouteRouteImport.update({
    id: '/purchase-manage',
    path: '/purchase-manage',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductionRouteRoute =
  DashboardProductionRouteRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersRouteRoute = DashboardOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFoodManagementRouteRoute =
  DashboardFoodManagementRouteRouteImport.update({
    id: '/food-management',
    path: '/food-management',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardRestaurantManagementIndexRoute =
  DashboardRestaurantManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRestaurantManagementRouteRoute,
  } as any)
const DashboardReservationsIndexRoute =
  DashboardReservationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardReservationsRouteRoute,
  } as any)
const DashboardPurchaseManageIndexRoute =
  DashboardPurchaseManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardProductionIndexRoute =
  DashboardProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrdersRouteRoute,
} as any)
const DashboardFoodManagementIndexRoute =
  DashboardFoodManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFoodManagementRouteRoute,
  } as any)
const DashboardChatsIndexRoute = DashboardChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsDisplayRoute =
  DashboardSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardRestaurantManagementManageTablesIndexRoute =
  DashboardRestaurantManagementManageTablesIndexRouteImport.update({
    id: '/manage-tables/',
    path: '/manage-tables/',
    getParentRoute: () => DashboardRestaurantManagementRouteRoute,
  } as any)
const DashboardRestaurantManagementManageKitchensIndexRoute =
  DashboardRestaurantManagementManageKitchensIndexRouteImport.update({
    id: '/manage-kitchens/',
    path: '/manage-kitchens/',
    getParentRoute: () => DashboardRestaurantManagementRouteRoute,
  } as any)
const DashboardReservationsUnavailableDayIndexRoute =
  DashboardReservationsUnavailableDayIndexRouteImport.update({
    id: '/unavailable-day/',
    path: '/unavailable-day/',
    getParentRoute: () => DashboardReservationsRouteRoute,
  } as any)
const DashboardReservationsSettingsIndexRoute =
  DashboardReservationsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardReservationsRouteRoute,
  } as any)
const DashboardPurchaseManageSupplierManageIndexRoute =
  DashboardPurchaseManageSupplierManageIndexRouteImport.update({
    id: '/supplier-manage/',
    path: '/supplier-manage/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManageSupplierLedgerIndexRoute =
  DashboardPurchaseManageSupplierLedgerIndexRouteImport.update({
    id: '/supplier-ledger/',
    path: '/supplier-ledger/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManageStockOutIngredientsIndexRoute =
  DashboardPurchaseManageStockOutIngredientsIndexRouteImport.update({
    id: '/stock-out-ingredients/',
    path: '/stock-out-ingredients/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManageReturnInvoiceIndexRoute =
  DashboardPurchaseManageReturnInvoiceIndexRouteImport.update({
    id: '/return-invoice/',
    path: '/return-invoice/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManagePurchaseReturnIndexRoute =
  DashboardPurchaseManagePurchaseReturnIndexRouteImport.update({
    id: '/purchase-return/',
    path: '/purchase-return/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManagePurchaseItemIndexRoute =
  DashboardPurchaseManagePurchaseItemIndexRouteImport.update({
    id: '/purchase-item/',
    path: '/purchase-item/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardPurchaseManageAddPurchaseIndexRoute =
  DashboardPurchaseManageAddPurchaseIndexRouteImport.update({
    id: '/add-purchase/',
    path: '/add-purchase/',
    getParentRoute: () => DashboardPurchaseManageRouteRoute,
  } as any)
const DashboardProductionSetProductionUnitIndexRoute =
  DashboardProductionSetProductionUnitIndexRouteImport.update({
    id: '/set-production-unit/',
    path: '/set-production-unit/',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)
const DashboardProductionProductionSettingIndexRoute =
  DashboardProductionProductionSettingIndexRouteImport.update({
    id: '/production-setting/',
    path: '/production-setting/',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)
const DashboardProductionProductionSetListIndexRoute =
  DashboardProductionProductionSetListIndexRouteImport.update({
    id: '/production-set-list/',
    path: '/production-set-list/',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)
const DashboardProductionAddProductionIndexRoute =
  DashboardProductionAddProductionIndexRouteImport.update({
    id: '/add-production/',
    path: '/add-production/',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)
const DashboardFoodManagementManageFoodIndexRoute =
  DashboardFoodManagementManageFoodIndexRouteImport.update({
    id: '/manage-food/',
    path: '/manage-food/',
    getParentRoute: () => DashboardFoodManagementRouteRoute,
  } as any)
const DashboardFoodManagementManageCategoryIndexRoute =
  DashboardFoodManagementManageCategoryIndexRouteImport.update({
    id: '/manage-category/',
    path: '/manage-category/',
    getParentRoute: () => DashboardFoodManagementRouteRoute,
  } as any)
const DashboardFoodManagementManageAddonsIndexRoute =
  DashboardFoodManagementManageAddonsIndexRouteImport.update({
    id: '/manage-addons/',
    path: '/manage-addons/',
    getParentRoute: () => DashboardFoodManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/counter-dashboard': typeof CounterDashboardRoute
  '/kitchen-dashboard': typeof KitchenDashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pos-invoice': typeof PosInvoiceRoute
  '/dashboard/food-management': typeof DashboardFoodManagementRouteRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRouteRouteWithChildren
  '/dashboard/production': typeof DashboardProductionRouteRouteWithChildren
  '/dashboard/purchase-manage': typeof DashboardPurchaseManageRouteRouteWithChildren
  '/dashboard/reservations': typeof DashboardReservationsRouteRouteWithChildren
  '/dashboard/restaurant-management': typeof DashboardRestaurantManagementRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in-2': typeof authSignIn2Route
  '/signup': typeof authSignupRoute
  '/signup-verify': typeof authSignupVerifyRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/apps': typeof DashboardAppsIndexRoute
  '/dashboard/chats': typeof DashboardChatsIndexRoute
  '/dashboard/food-management/': typeof DashboardFoodManagementIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/production/': typeof DashboardProductionIndexRoute
  '/dashboard/purchase-manage/': typeof DashboardPurchaseManageIndexRoute
  '/dashboard/reservations/': typeof DashboardReservationsIndexRoute
  '/dashboard/restaurant-management/': typeof DashboardRestaurantManagementIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/food-management/manage-addons': typeof DashboardFoodManagementManageAddonsIndexRoute
  '/dashboard/food-management/manage-category': typeof DashboardFoodManagementManageCategoryIndexRoute
  '/dashboard/food-management/manage-food': typeof DashboardFoodManagementManageFoodIndexRoute
  '/dashboard/production/add-production': typeof DashboardProductionAddProductionIndexRoute
  '/dashboard/production/production-set-list': typeof DashboardProductionProductionSetListIndexRoute
  '/dashboard/production/production-setting': typeof DashboardProductionProductionSettingIndexRoute
  '/dashboard/production/set-production-unit': typeof DashboardProductionSetProductionUnitIndexRoute
  '/dashboard/purchase-manage/add-purchase': typeof DashboardPurchaseManageAddPurchaseIndexRoute
  '/dashboard/purchase-manage/purchase-item': typeof DashboardPurchaseManagePurchaseItemIndexRoute
  '/dashboard/purchase-manage/purchase-return': typeof DashboardPurchaseManagePurchaseReturnIndexRoute
  '/dashboard/purchase-manage/return-invoice': typeof DashboardPurchaseManageReturnInvoiceIndexRoute
  '/dashboard/purchase-manage/stock-out-ingredients': typeof DashboardPurchaseManageStockOutIngredientsIndexRoute
  '/dashboard/purchase-manage/supplier-ledger': typeof DashboardPurchaseManageSupplierLedgerIndexRoute
  '/dashboard/purchase-manage/supplier-manage': typeof DashboardPurchaseManageSupplierManageIndexRoute
  '/dashboard/reservations/settings': typeof DashboardReservationsSettingsIndexRoute
  '/dashboard/reservations/unavailable-day': typeof DashboardReservationsUnavailableDayIndexRoute
  '/dashboard/restaurant-management/manage-kitchens': typeof DashboardRestaurantManagementManageKitchensIndexRoute
  '/dashboard/restaurant-management/manage-tables': typeof DashboardRestaurantManagementManageTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/counter-dashboard': typeof CounterDashboardRoute
  '/kitchen-dashboard': typeof KitchenDashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pos-invoice': typeof PosInvoiceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in-2': typeof authSignIn2Route
  '/signup': typeof authSignupRoute
  '/signup-verify': typeof authSignupVerifyRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/apps': typeof DashboardAppsIndexRoute
  '/dashboard/chats': typeof DashboardChatsIndexRoute
  '/dashboard/food-management': typeof DashboardFoodManagementIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/production': typeof DashboardProductionIndexRoute
  '/dashboard/purchase-manage': typeof DashboardPurchaseManageIndexRoute
  '/dashboard/reservations': typeof DashboardReservationsIndexRoute
  '/dashboard/restaurant-management': typeof DashboardRestaurantManagementIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/food-management/manage-addons': typeof DashboardFoodManagementManageAddonsIndexRoute
  '/dashboard/food-management/manage-category': typeof DashboardFoodManagementManageCategoryIndexRoute
  '/dashboard/food-management/manage-food': typeof DashboardFoodManagementManageFoodIndexRoute
  '/dashboard/production/add-production': typeof DashboardProductionAddProductionIndexRoute
  '/dashboard/production/production-set-list': typeof DashboardProductionProductionSetListIndexRoute
  '/dashboard/production/production-setting': typeof DashboardProductionProductionSettingIndexRoute
  '/dashboard/production/set-production-unit': typeof DashboardProductionSetProductionUnitIndexRoute
  '/dashboard/purchase-manage/add-purchase': typeof DashboardPurchaseManageAddPurchaseIndexRoute
  '/dashboard/purchase-manage/purchase-item': typeof DashboardPurchaseManagePurchaseItemIndexRoute
  '/dashboard/purchase-manage/purchase-return': typeof DashboardPurchaseManagePurchaseReturnIndexRoute
  '/dashboard/purchase-manage/return-invoice': typeof DashboardPurchaseManageReturnInvoiceIndexRoute
  '/dashboard/purchase-manage/stock-out-ingredients': typeof DashboardPurchaseManageStockOutIngredientsIndexRoute
  '/dashboard/purchase-manage/supplier-ledger': typeof DashboardPurchaseManageSupplierLedgerIndexRoute
  '/dashboard/purchase-manage/supplier-manage': typeof DashboardPurchaseManageSupplierManageIndexRoute
  '/dashboard/reservations/settings': typeof DashboardReservationsSettingsIndexRoute
  '/dashboard/reservations/unavailable-day': typeof DashboardReservationsUnavailableDayIndexRoute
  '/dashboard/restaurant-management/manage-kitchens': typeof DashboardRestaurantManagementManageKitchensIndexRoute
  '/dashboard/restaurant-management/manage-tables': typeof DashboardRestaurantManagementManageTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/counter-dashboard': typeof CounterDashboardRoute
  '/kitchen-dashboard': typeof KitchenDashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pos-invoice': typeof PosInvoiceRoute
  '/dashboard/food-management': typeof DashboardFoodManagementRouteRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRouteRouteWithChildren
  '/dashboard/production': typeof DashboardProductionRouteRouteWithChildren
  '/dashboard/purchase-manage': typeof DashboardPurchaseManageRouteRouteWithChildren
  '/dashboard/reservations': typeof DashboardReservationsRouteRouteWithChildren
  '/dashboard/restaurant-management': typeof DashboardRestaurantManagementRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/signup-verify': typeof authSignupVerifyRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/apps/': typeof DashboardAppsIndexRoute
  '/dashboard/chats/': typeof DashboardChatsIndexRoute
  '/dashboard/food-management/': typeof DashboardFoodManagementIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/production/': typeof DashboardProductionIndexRoute
  '/dashboard/purchase-manage/': typeof DashboardPurchaseManageIndexRoute
  '/dashboard/reservations/': typeof DashboardReservationsIndexRoute
  '/dashboard/restaurant-management/': typeof DashboardRestaurantManagementIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/food-management/manage-addons/': typeof DashboardFoodManagementManageAddonsIndexRoute
  '/dashboard/food-management/manage-category/': typeof DashboardFoodManagementManageCategoryIndexRoute
  '/dashboard/food-management/manage-food/': typeof DashboardFoodManagementManageFoodIndexRoute
  '/dashboard/production/add-production/': typeof DashboardProductionAddProductionIndexRoute
  '/dashboard/production/production-set-list/': typeof DashboardProductionProductionSetListIndexRoute
  '/dashboard/production/production-setting/': typeof DashboardProductionProductionSettingIndexRoute
  '/dashboard/production/set-production-unit/': typeof DashboardProductionSetProductionUnitIndexRoute
  '/dashboard/purchase-manage/add-purchase/': typeof DashboardPurchaseManageAddPurchaseIndexRoute
  '/dashboard/purchase-manage/purchase-item/': typeof DashboardPurchaseManagePurchaseItemIndexRoute
  '/dashboard/purchase-manage/purchase-return/': typeof DashboardPurchaseManagePurchaseReturnIndexRoute
  '/dashboard/purchase-manage/return-invoice/': typeof DashboardPurchaseManageReturnInvoiceIndexRoute
  '/dashboard/purchase-manage/stock-out-ingredients/': typeof DashboardPurchaseManageStockOutIngredientsIndexRoute
  '/dashboard/purchase-manage/supplier-ledger/': typeof DashboardPurchaseManageSupplierLedgerIndexRoute
  '/dashboard/purchase-manage/supplier-manage/': typeof DashboardPurchaseManageSupplierManageIndexRoute
  '/dashboard/reservations/settings/': typeof DashboardReservationsSettingsIndexRoute
  '/dashboard/reservations/unavailable-day/': typeof DashboardReservationsUnavailableDayIndexRoute
  '/dashboard/restaurant-management/manage-kitchens/': typeof DashboardRestaurantManagementManageKitchensIndexRoute
  '/dashboard/restaurant-management/manage-tables/': typeof DashboardRestaurantManagementManageTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/counter-dashboard'
    | '/kitchen-dashboard'
    | '/onboarding'
    | '/pos-invoice'
    | '/dashboard/food-management'
    | '/dashboard/orders'
    | '/dashboard/production'
    | '/dashboard/purchase-manage'
    | '/dashboard/reservations'
    | '/dashboard/restaurant-management'
    | '/dashboard/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in-2'
    | '/signup'
    | '/signup-verify'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps'
    | '/dashboard/chats'
    | '/dashboard/food-management/'
    | '/dashboard/orders/'
    | '/dashboard/production/'
    | '/dashboard/purchase-manage/'
    | '/dashboard/reservations/'
    | '/dashboard/restaurant-management/'
    | '/dashboard/settings/'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/food-management/manage-addons'
    | '/dashboard/food-management/manage-category'
    | '/dashboard/food-management/manage-food'
    | '/dashboard/production/add-production'
    | '/dashboard/production/production-set-list'
    | '/dashboard/production/production-setting'
    | '/dashboard/production/set-production-unit'
    | '/dashboard/purchase-manage/add-purchase'
    | '/dashboard/purchase-manage/purchase-item'
    | '/dashboard/purchase-manage/purchase-return'
    | '/dashboard/purchase-manage/return-invoice'
    | '/dashboard/purchase-manage/stock-out-ingredients'
    | '/dashboard/purchase-manage/supplier-ledger'
    | '/dashboard/purchase-manage/supplier-manage'
    | '/dashboard/reservations/settings'
    | '/dashboard/reservations/unavailable-day'
    | '/dashboard/restaurant-management/manage-kitchens'
    | '/dashboard/restaurant-management/manage-tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/counter-dashboard'
    | '/kitchen-dashboard'
    | '/onboarding'
    | '/pos-invoice'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in-2'
    | '/signup'
    | '/signup-verify'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps'
    | '/dashboard/chats'
    | '/dashboard/food-management'
    | '/dashboard/orders'
    | '/dashboard/production'
    | '/dashboard/purchase-manage'
    | '/dashboard/reservations'
    | '/dashboard/restaurant-management'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/food-management/manage-addons'
    | '/dashboard/food-management/manage-category'
    | '/dashboard/food-management/manage-food'
    | '/dashboard/production/add-production'
    | '/dashboard/production/production-set-list'
    | '/dashboard/production/production-setting'
    | '/dashboard/production/set-production-unit'
    | '/dashboard/purchase-manage/add-purchase'
    | '/dashboard/purchase-manage/purchase-item'
    | '/dashboard/purchase-manage/purchase-return'
    | '/dashboard/purchase-manage/return-invoice'
    | '/dashboard/purchase-manage/stock-out-ingredients'
    | '/dashboard/purchase-manage/supplier-ledger'
    | '/dashboard/purchase-manage/supplier-manage'
    | '/dashboard/reservations/settings'
    | '/dashboard/reservations/unavailable-day'
    | '/dashboard/restaurant-management/manage-kitchens'
    | '/dashboard/restaurant-management/manage-tables'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/counter-dashboard'
    | '/kitchen-dashboard'
    | '/onboarding'
    | '/pos-invoice'
    | '/dashboard/food-management'
    | '/dashboard/orders'
    | '/dashboard/production'
    | '/dashboard/purchase-manage'
    | '/dashboard/reservations'
    | '/dashboard/restaurant-management'
    | '/dashboard/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-in-2'
    | '/(auth)/signup'
    | '/(auth)/signup-verify'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps/'
    | '/dashboard/chats/'
    | '/dashboard/food-management/'
    | '/dashboard/orders/'
    | '/dashboard/production/'
    | '/dashboard/purchase-manage/'
    | '/dashboard/reservations/'
    | '/dashboard/restaurant-management/'
    | '/dashboard/settings/'
    | '/dashboard/tasks/'
    | '/dashboard/users/'
    | '/dashboard/food-management/manage-addons/'
    | '/dashboard/food-management/manage-category/'
    | '/dashboard/food-management/manage-food/'
    | '/dashboard/production/add-production/'
    | '/dashboard/production/production-set-list/'
    | '/dashboard/production/production-setting/'
    | '/dashboard/production/set-production-unit/'
    | '/dashboard/purchase-manage/add-purchase/'
    | '/dashboard/purchase-manage/purchase-item/'
    | '/dashboard/purchase-manage/purchase-return/'
    | '/dashboard/purchase-manage/return-invoice/'
    | '/dashboard/purchase-manage/stock-out-ingredients/'
    | '/dashboard/purchase-manage/supplier-ledger/'
    | '/dashboard/purchase-manage/supplier-manage/'
    | '/dashboard/reservations/settings/'
    | '/dashboard/reservations/unavailable-day/'
    | '/dashboard/restaurant-management/manage-kitchens/'
    | '/dashboard/restaurant-management/manage-tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CounterDashboardRoute: typeof CounterDashboardRoute
  KitchenDashboardRoute: typeof KitchenDashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PosInvoiceRoute: typeof PosInvoiceRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos-invoice': {
      id: '/pos-invoice'
      path: '/pos-invoice'
      fullPath: '/pos-invoice'
      preLoaderRoute: typeof PosInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-dashboard': {
      id: '/kitchen-dashboard'
      path: '/kitchen-dashboard'
      fullPath: '/kitchen-dashboard'
      preLoaderRoute: typeof KitchenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter-dashboard': {
      id: '/counter-dashboard'
      path: '/counter-dashboard'
      fullPath: '/counter-dashboard'
      preLoaderRoute: typeof CounterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup-verify': {
      id: '/(auth)/signup-verify'
      path: '/signup-verify'
      fullPath: '/signup-verify'
      preLoaderRoute: typeof authSignupVerifyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/restaurant-management': {
      id: '/dashboard/restaurant-management'
      path: '/restaurant-management'
      fullPath: '/dashboard/restaurant-management'
      preLoaderRoute: typeof DashboardRestaurantManagementRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations': {
      id: '/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/purchase-manage': {
      id: '/dashboard/purchase-manage'
      path: '/purchase-manage'
      fullPath: '/dashboard/purchase-manage'
      preLoaderRoute: typeof DashboardPurchaseManageRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/production': {
      id: '/dashboard/production'
      path: '/production'
      fullPath: '/dashboard/production'
      preLoaderRoute: typeof DashboardProductionRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/food-management': {
      id: '/dashboard/food-management'
      path: '/food-management'
      fullPath: '/dashboard/food-management'
      preLoaderRoute: typeof DashboardFoodManagementRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/restaurant-management/': {
      id: '/dashboard/restaurant-management/'
      path: '/'
      fullPath: '/dashboard/restaurant-management/'
      preLoaderRoute: typeof DashboardRestaurantManagementIndexRouteImport
      parentRoute: typeof DashboardRestaurantManagementRouteRoute
    }
    '/dashboard/reservations/': {
      id: '/dashboard/reservations/'
      path: '/'
      fullPath: '/dashboard/reservations/'
      preLoaderRoute: typeof DashboardReservationsIndexRouteImport
      parentRoute: typeof DashboardReservationsRouteRoute
    }
    '/dashboard/purchase-manage/': {
      id: '/dashboard/purchase-manage/'
      path: '/'
      fullPath: '/dashboard/purchase-manage/'
      preLoaderRoute: typeof DashboardPurchaseManageIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/production/': {
      id: '/dashboard/production/'
      path: '/'
      fullPath: '/dashboard/production/'
      preLoaderRoute: typeof DashboardProductionIndexRouteImport
      parentRoute: typeof DashboardProductionRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardOrdersRouteRoute
    }
    '/dashboard/food-management/': {
      id: '/dashboard/food-management/'
      path: '/'
      fullPath: '/dashboard/food-management/'
      preLoaderRoute: typeof DashboardFoodManagementIndexRouteImport
      parentRoute: typeof DashboardFoodManagementRouteRoute
    }
    '/dashboard/chats/': {
      id: '/dashboard/chats/'
      path: '/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof DashboardChatsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/apps/': {
      id: '/dashboard/apps/'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/display': {
      id: '/dashboard/settings/display'
      path: '/display'
      fullPath: '/dashboard/settings/display'
      preLoaderRoute: typeof DashboardSettingsDisplayRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/restaurant-management/manage-tables/': {
      id: '/dashboard/restaurant-management/manage-tables/'
      path: '/manage-tables'
      fullPath: '/dashboard/restaurant-management/manage-tables'
      preLoaderRoute: typeof DashboardRestaurantManagementManageTablesIndexRouteImport
      parentRoute: typeof DashboardRestaurantManagementRouteRoute
    }
    '/dashboard/restaurant-management/manage-kitchens/': {
      id: '/dashboard/restaurant-management/manage-kitchens/'
      path: '/manage-kitchens'
      fullPath: '/dashboard/restaurant-management/manage-kitchens'
      preLoaderRoute: typeof DashboardRestaurantManagementManageKitchensIndexRouteImport
      parentRoute: typeof DashboardRestaurantManagementRouteRoute
    }
    '/dashboard/reservations/unavailable-day/': {
      id: '/dashboard/reservations/unavailable-day/'
      path: '/unavailable-day'
      fullPath: '/dashboard/reservations/unavailable-day'
      preLoaderRoute: typeof DashboardReservationsUnavailableDayIndexRouteImport
      parentRoute: typeof DashboardReservationsRouteRoute
    }
    '/dashboard/reservations/settings/': {
      id: '/dashboard/reservations/settings/'
      path: '/settings'
      fullPath: '/dashboard/reservations/settings'
      preLoaderRoute: typeof DashboardReservationsSettingsIndexRouteImport
      parentRoute: typeof DashboardReservationsRouteRoute
    }
    '/dashboard/purchase-manage/supplier-manage/': {
      id: '/dashboard/purchase-manage/supplier-manage/'
      path: '/supplier-manage'
      fullPath: '/dashboard/purchase-manage/supplier-manage'
      preLoaderRoute: typeof DashboardPurchaseManageSupplierManageIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/supplier-ledger/': {
      id: '/dashboard/purchase-manage/supplier-ledger/'
      path: '/supplier-ledger'
      fullPath: '/dashboard/purchase-manage/supplier-ledger'
      preLoaderRoute: typeof DashboardPurchaseManageSupplierLedgerIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/stock-out-ingredients/': {
      id: '/dashboard/purchase-manage/stock-out-ingredients/'
      path: '/stock-out-ingredients'
      fullPath: '/dashboard/purchase-manage/stock-out-ingredients'
      preLoaderRoute: typeof DashboardPurchaseManageStockOutIngredientsIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/return-invoice/': {
      id: '/dashboard/purchase-manage/return-invoice/'
      path: '/return-invoice'
      fullPath: '/dashboard/purchase-manage/return-invoice'
      preLoaderRoute: typeof DashboardPurchaseManageReturnInvoiceIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/purchase-return/': {
      id: '/dashboard/purchase-manage/purchase-return/'
      path: '/purchase-return'
      fullPath: '/dashboard/purchase-manage/purchase-return'
      preLoaderRoute: typeof DashboardPurchaseManagePurchaseReturnIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/purchase-item/': {
      id: '/dashboard/purchase-manage/purchase-item/'
      path: '/purchase-item'
      fullPath: '/dashboard/purchase-manage/purchase-item'
      preLoaderRoute: typeof DashboardPurchaseManagePurchaseItemIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/purchase-manage/add-purchase/': {
      id: '/dashboard/purchase-manage/add-purchase/'
      path: '/add-purchase'
      fullPath: '/dashboard/purchase-manage/add-purchase'
      preLoaderRoute: typeof DashboardPurchaseManageAddPurchaseIndexRouteImport
      parentRoute: typeof DashboardPurchaseManageRouteRoute
    }
    '/dashboard/production/set-production-unit/': {
      id: '/dashboard/production/set-production-unit/'
      path: '/set-production-unit'
      fullPath: '/dashboard/production/set-production-unit'
      preLoaderRoute: typeof DashboardProductionSetProductionUnitIndexRouteImport
      parentRoute: typeof DashboardProductionRouteRoute
    }
    '/dashboard/production/production-setting/': {
      id: '/dashboard/production/production-setting/'
      path: '/production-setting'
      fullPath: '/dashboard/production/production-setting'
      preLoaderRoute: typeof DashboardProductionProductionSettingIndexRouteImport
      parentRoute: typeof DashboardProductionRouteRoute
    }
    '/dashboard/production/production-set-list/': {
      id: '/dashboard/production/production-set-list/'
      path: '/production-set-list'
      fullPath: '/dashboard/production/production-set-list'
      preLoaderRoute: typeof DashboardProductionProductionSetListIndexRouteImport
      parentRoute: typeof DashboardProductionRouteRoute
    }
    '/dashboard/production/add-production/': {
      id: '/dashboard/production/add-production/'
      path: '/add-production'
      fullPath: '/dashboard/production/add-production'
      preLoaderRoute: typeof DashboardProductionAddProductionIndexRouteImport
      parentRoute: typeof DashboardProductionRouteRoute
    }
    '/dashboard/food-management/manage-food/': {
      id: '/dashboard/food-management/manage-food/'
      path: '/manage-food'
      fullPath: '/dashboard/food-management/manage-food'
      preLoaderRoute: typeof DashboardFoodManagementManageFoodIndexRouteImport
      parentRoute: typeof DashboardFoodManagementRouteRoute
    }
    '/dashboard/food-management/manage-category/': {
      id: '/dashboard/food-management/manage-category/'
      path: '/manage-category'
      fullPath: '/dashboard/food-management/manage-category'
      preLoaderRoute: typeof DashboardFoodManagementManageCategoryIndexRouteImport
      parentRoute: typeof DashboardFoodManagementRouteRoute
    }
    '/dashboard/food-management/manage-addons/': {
      id: '/dashboard/food-management/manage-addons/'
      path: '/manage-addons'
      fullPath: '/dashboard/food-management/manage-addons'
      preLoaderRoute: typeof DashboardFoodManagementManageAddonsIndexRouteImport
      parentRoute: typeof DashboardFoodManagementRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignupRoute: typeof authSignupRoute
  authSignupVerifyRoute: typeof authSignupVerifyRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignIn2Route: authSignIn2Route,
  authSignupRoute: authSignupRoute,
  authSignupVerifyRoute: authSignupVerifyRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardFoodManagementRouteRouteChildren {
  DashboardFoodManagementIndexRoute: typeof DashboardFoodManagementIndexRoute
  DashboardFoodManagementManageAddonsIndexRoute: typeof DashboardFoodManagementManageAddonsIndexRoute
  DashboardFoodManagementManageCategoryIndexRoute: typeof DashboardFoodManagementManageCategoryIndexRoute
  DashboardFoodManagementManageFoodIndexRoute: typeof DashboardFoodManagementManageFoodIndexRoute
}

const DashboardFoodManagementRouteRouteChildren: DashboardFoodManagementRouteRouteChildren =
  {
    DashboardFoodManagementIndexRoute: DashboardFoodManagementIndexRoute,
    DashboardFoodManagementManageAddonsIndexRoute:
      DashboardFoodManagementManageAddonsIndexRoute,
    DashboardFoodManagementManageCategoryIndexRoute:
      DashboardFoodManagementManageCategoryIndexRoute,
    DashboardFoodManagementManageFoodIndexRoute:
      DashboardFoodManagementManageFoodIndexRoute,
  }

const DashboardFoodManagementRouteRouteWithChildren =
  DashboardFoodManagementRouteRoute._addFileChildren(
    DashboardFoodManagementRouteRouteChildren,
  )

interface DashboardOrdersRouteRouteChildren {
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardOrdersRouteRouteChildren: DashboardOrdersRouteRouteChildren = {
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardOrdersRouteRouteWithChildren =
  DashboardOrdersRouteRoute._addFileChildren(DashboardOrdersRouteRouteChildren)

interface DashboardProductionRouteRouteChildren {
  DashboardProductionIndexRoute: typeof DashboardProductionIndexRoute
  DashboardProductionAddProductionIndexRoute: typeof DashboardProductionAddProductionIndexRoute
  DashboardProductionProductionSetListIndexRoute: typeof DashboardProductionProductionSetListIndexRoute
  DashboardProductionProductionSettingIndexRoute: typeof DashboardProductionProductionSettingIndexRoute
  DashboardProductionSetProductionUnitIndexRoute: typeof DashboardProductionSetProductionUnitIndexRoute
}

const DashboardProductionRouteRouteChildren: DashboardProductionRouteRouteChildren =
  {
    DashboardProductionIndexRoute: DashboardProductionIndexRoute,
    DashboardProductionAddProductionIndexRoute:
      DashboardProductionAddProductionIndexRoute,
    DashboardProductionProductionSetListIndexRoute:
      DashboardProductionProductionSetListIndexRoute,
    DashboardProductionProductionSettingIndexRoute:
      DashboardProductionProductionSettingIndexRoute,
    DashboardProductionSetProductionUnitIndexRoute:
      DashboardProductionSetProductionUnitIndexRoute,
  }

const DashboardProductionRouteRouteWithChildren =
  DashboardProductionRouteRoute._addFileChildren(
    DashboardProductionRouteRouteChildren,
  )

interface DashboardPurchaseManageRouteRouteChildren {
  DashboardPurchaseManageIndexRoute: typeof DashboardPurchaseManageIndexRoute
  DashboardPurchaseManageAddPurchaseIndexRoute: typeof DashboardPurchaseManageAddPurchaseIndexRoute
  DashboardPurchaseManagePurchaseItemIndexRoute: typeof DashboardPurchaseManagePurchaseItemIndexRoute
  DashboardPurchaseManagePurchaseReturnIndexRoute: typeof DashboardPurchaseManagePurchaseReturnIndexRoute
  DashboardPurchaseManageReturnInvoiceIndexRoute: typeof DashboardPurchaseManageReturnInvoiceIndexRoute
  DashboardPurchaseManageStockOutIngredientsIndexRoute: typeof DashboardPurchaseManageStockOutIngredientsIndexRoute
  DashboardPurchaseManageSupplierLedgerIndexRoute: typeof DashboardPurchaseManageSupplierLedgerIndexRoute
  DashboardPurchaseManageSupplierManageIndexRoute: typeof DashboardPurchaseManageSupplierManageIndexRoute
}

const DashboardPurchaseManageRouteRouteChildren: DashboardPurchaseManageRouteRouteChildren =
  {
    DashboardPurchaseManageIndexRoute: DashboardPurchaseManageIndexRoute,
    DashboardPurchaseManageAddPurchaseIndexRoute:
      DashboardPurchaseManageAddPurchaseIndexRoute,
    DashboardPurchaseManagePurchaseItemIndexRoute:
      DashboardPurchaseManagePurchaseItemIndexRoute,
    DashboardPurchaseManagePurchaseReturnIndexRoute:
      DashboardPurchaseManagePurchaseReturnIndexRoute,
    DashboardPurchaseManageReturnInvoiceIndexRoute:
      DashboardPurchaseManageReturnInvoiceIndexRoute,
    DashboardPurchaseManageStockOutIngredientsIndexRoute:
      DashboardPurchaseManageStockOutIngredientsIndexRoute,
    DashboardPurchaseManageSupplierLedgerIndexRoute:
      DashboardPurchaseManageSupplierLedgerIndexRoute,
    DashboardPurchaseManageSupplierManageIndexRoute:
      DashboardPurchaseManageSupplierManageIndexRoute,
  }

const DashboardPurchaseManageRouteRouteWithChildren =
  DashboardPurchaseManageRouteRoute._addFileChildren(
    DashboardPurchaseManageRouteRouteChildren,
  )

interface DashboardReservationsRouteRouteChildren {
  DashboardReservationsIndexRoute: typeof DashboardReservationsIndexRoute
  DashboardReservationsSettingsIndexRoute: typeof DashboardReservationsSettingsIndexRoute
  DashboardReservationsUnavailableDayIndexRoute: typeof DashboardReservationsUnavailableDayIndexRoute
}

const DashboardReservationsRouteRouteChildren: DashboardReservationsRouteRouteChildren =
  {
    DashboardReservationsIndexRoute: DashboardReservationsIndexRoute,
    DashboardReservationsSettingsIndexRoute:
      DashboardReservationsSettingsIndexRoute,
    DashboardReservationsUnavailableDayIndexRoute:
      DashboardReservationsUnavailableDayIndexRoute,
  }

const DashboardReservationsRouteRouteWithChildren =
  DashboardReservationsRouteRoute._addFileChildren(
    DashboardReservationsRouteRouteChildren,
  )

interface DashboardRestaurantManagementRouteRouteChildren {
  DashboardRestaurantManagementIndexRoute: typeof DashboardRestaurantManagementIndexRoute
  DashboardRestaurantManagementManageKitchensIndexRoute: typeof DashboardRestaurantManagementManageKitchensIndexRoute
  DashboardRestaurantManagementManageTablesIndexRoute: typeof DashboardRestaurantManagementManageTablesIndexRoute
}

const DashboardRestaurantManagementRouteRouteChildren: DashboardRestaurantManagementRouteRouteChildren =
  {
    DashboardRestaurantManagementIndexRoute:
      DashboardRestaurantManagementIndexRoute,
    DashboardRestaurantManagementManageKitchensIndexRoute:
      DashboardRestaurantManagementManageKitchensIndexRoute,
    DashboardRestaurantManagementManageTablesIndexRoute:
      DashboardRestaurantManagementManageTablesIndexRoute,
  }

const DashboardRestaurantManagementRouteRouteWithChildren =
  DashboardRestaurantManagementRouteRoute._addFileChildren(
    DashboardRestaurantManagementRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsDisplayRoute: typeof DashboardSettingsDisplayRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
    DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
    DashboardSettingsDisplayRoute: DashboardSettingsDisplayRoute,
    DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardFoodManagementRouteRoute: typeof DashboardFoodManagementRouteRouteWithChildren
  DashboardOrdersRouteRoute: typeof DashboardOrdersRouteRouteWithChildren
  DashboardProductionRouteRoute: typeof DashboardProductionRouteRouteWithChildren
  DashboardPurchaseManageRouteRoute: typeof DashboardPurchaseManageRouteRouteWithChildren
  DashboardReservationsRouteRoute: typeof DashboardReservationsRouteRouteWithChildren
  DashboardRestaurantManagementRouteRoute: typeof DashboardRestaurantManagementRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
  DashboardChatsIndexRoute: typeof DashboardChatsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFoodManagementRouteRoute:
    DashboardFoodManagementRouteRouteWithChildren,
  DashboardOrdersRouteRoute: DashboardOrdersRouteRouteWithChildren,
  DashboardProductionRouteRoute: DashboardProductionRouteRouteWithChildren,
  DashboardPurchaseManageRouteRoute:
    DashboardPurchaseManageRouteRouteWithChildren,
  DashboardReservationsRouteRoute: DashboardReservationsRouteRouteWithChildren,
  DashboardRestaurantManagementRouteRoute:
    DashboardRestaurantManagementRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
  DashboardChatsIndexRoute: DashboardChatsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CounterDashboardRoute: CounterDashboardRoute,
  KitchenDashboardRoute: KitchenDashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PosInvoiceRoute: PosInvoiceRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
